lexical_es = {'first_person_singular': ['yo', 'mio', 'mi'],
              'second_person_singular': ['tú', 'tu', 'tuyo', 'usted', 'vos'],
              'third_person_singular': ['él', 'el', 'ella', 'ese', 'esa', 'aquel'],
              'first_person_plurar': ['nosotros', 'nuestros'],
              'second_person_plurar': ['tuyos', 'tuyas', 'ustedes', 'vosotros', 'vosotras'],
              'third_person_plurar': ['ellos', 'ellas', 'ese', 'esos', 'aquellas', 'aquellos'],
              'adverb_time': ['ya', 'aún', 'hoy', 'tarde', 'pronto', 'todavía', 'ayer', 'recién', 'nunca', 'siempre',
                              'jamás', 'ahora'],
              'adverb_neg': ['tampoco', 'no', 'en absoluto', 'nunca'],
              'adverb_place': ['ahí', 'allí', 'aquí', 'acá', 'delante', 'detrás', 'arriba', 'abajo', 'cerca', 'lejos',
                               'encima', 'fuera', 'dentro'],
              'adverb_mode': ['mal', 'bien', 'regular', 'despacio', 'así', 'mejor', 'peor', 'claro', 'similar',
                              'fácilmente'],
              'adverb_cant': ['muy', 'más', 'poco', 'bastante', 'bastante', 'menos', 'mucho', 'algo', 'casi'],
              'adjetives_neg': ['aburrido', 'ácido', 'amargo', 'ancho', 'atrevido', 'bajo', 'blando', 'caliente',
                                'común', 'conocido', 'corto', 'débil', 'delgado', 'diferente', 'difícil', 'duro',
                                'enfermo', 'estrecho', 'falso', 'feo', 'frío', 'húmedo', 'imposible', 'izquierdo',
                                'lento', 'malo', 'menor', 'muerto', 'negro', 'peor', 'pequeño', 'pobre', 'poco',
                                'popular', 'raro', 'rojo', 'salado', 'simple', 'sinvergüenza', 'solo', 'soso',
                                'tímido', 'tonto', 'triste', 'viejo'],
              'adjetives_pos': ['alegre', 'alto', 'azul', 'blanco', 'bonito', 'buen', 'bueno', 'caliente', 'capaz',
                                'central', 'contento', 'derecho', 'diferente', 'divertido', 'dulce', 'duro', 'exterior',
                                'famoso', 'final', 'fresco', 'fuerte', 'gran', 'grande', 'guapo', 'guay', 'igual',
                                'imposible', 'interesante', 'joven', 'largo', 'listo', 'mayor', 'mejor', 'mucho',
                                'musical', 'nacional', 'natural', 'nuevo', 'perfecto', 'popular', 'posible',
                                'primer', 'primero', 'principal', 'próximo', 'rápido', 'real', 'recto', 'rico',
                                'salado', 'sano', 'seco', 'útil', 'verdadero', 'verde', 'vivo'],
              'who_general': ['familia', 'familiar', 'familiares', 'acompañante', 'aprendices', 'aprendiz', 'artista',
                              'asistente', 'compinche', 'directiva', 'directivo', 'especialista', 'estudiante',
                              'estudiantes', 'joven', 'jovenes', 'lider', 'pareja', 'projimo'],
              'who_male': ['abuelo', 'alcalde', 'medico', 'alumno', 'alumnos', 'amigo', 'amigos', 'asesor', 'chiquillo',
                           'compa', 'compadre', 'compañero', 'compañeros', 'decano', 'director', 'doctor', 'empleado',
                           'empresario', 'entrenador', 'esposo', 'esposito', 'experto', 'expertos', 'funcionario',
                           'hermano', 'ingeniero', 'investigador', 'jefe', 'jugador', 'padre', 'marido', 'medico',
                           'muchacho', 'muchachos', 'niño', 'niños', 'novio', 'hijo', 'primo', 'papa', 'pequeños',
                           'profesor', 'pequeño', 'secretario', 'socio', 'tutor', 'papi', 'tio', 'nieto'],
              'who_female': ['alumna', 'alumnas', 'amiga', 'amigas', 'asesora', 'chiquilla', 'comadre', 'compañera',
                             'compañeras', 'dama', 'decana', 'directora', 'doctora', 'empleada', 'empresaria', 'esposa',
                             'esposita', 'experta', 'expertas', 'funcionaria', 'hermana', 'ingeniera', 'investigadora',
                             'jefa', 'jugadora', 'madre', 'mama', 'medica', 'muchacha', 'muchachas', 'mujer', 'niñas',
                             'novia', 'novicia', 'hija', 'prima', 'pequeña', 'pequeñas', 'profesora', 'secretaria',
                             'señora', 'socia', 'tutora', 'mami', 'tia', 'nieta']
              }

lexical_en = {'first_person_singular': ['i', 'me', 'my', 'mine', 'myself'],
              'second_person_singular': ['you', 'your', 'yours', 'yourself'],
              'third_person_singular': ['he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its',
                                        'itself'],
              'first_person_plurar': ['we', 'us', 'our', 'ours', 'ourselves'],
              'second_person_plurar': ['you', 'your', 'yours', 'yourself'],
              'third_person_plurar': ['they', 'them', 'their', 'theirs', 'themselves'],
              'adverb_time': ['now', 'then', 'today', 'tomorrow', 'tonight', 'yesterday', 'annually', 'daily',
                              'fortnightly', 'hourly', 'monthly', 'nightly', 'quarterly', 'weekly', 'yearly', 'always',
                              'constantly', 'ever', 'frequently', 'generally', 'infrequently', 'never', 'normally',
                              'occasionally', 'often', 'rarely', 'regularly', 'seldom', 'sometimes', 'regularly',
                              'usually', 'already', 'before', 'early', 'earlier', 'eventually', 'finally', 'first',
                              'formerly', 'just', 'last', 'late', 'later', 'lately', 'next', 'previously', 'recently',
                              'since', 'soon', 'still', 'yet'],
              'adverb_neg': ['no', 'not', 'angrily', 'anxiously', 'badly', 'boastfully', 'foolishly', 'hopelessly',
                             'irritably', 'jealously', 'lazily', 'obnoxiously', 'poorly', 'rudely', 'selfishly',
                             'wearily'],
              'adverb_place': ['about', 'above', 'abroad', 'anywhere', 'away', 'back', 'backwards', 'backward', 'behind',
                               'below', 'down', 'downstairs', 'east', 'elsewhere', 'far', 'here', 'in', 'indoors',
                               'inside', 'near', 'nearby', 'off', 'on', 'out', 'outside', 'over', 'there', 'towards',
                               'under', 'up', 'upstairs', 'where'],
              'adverb_mode': ['angrily', 'anxiously', 'awkwardly', 'badly', 'beautifully','calmly', 'carefully',
                              'carelessly', 'cautiously', 'cheerfully', 'clearly', 'closely', 'correctly',
                              'deliberately'],
              'adverb_cant': ['a few', 'a little', 'a lot of', 'almost', 'enough', 'entirely', 'even', 'failry',
                              'hardly', 'lots', 'less', 'many', 'much', 'partially', 'pretty', 'rather', 'quite',
                              'scarcely', 'so', 'too', 'very', 'way'],
              'adjetives_neg': ['aggressive', 'arrogant', 'boastful', 'bossy', 'boring', 'careless', 'clingy', 'cruel',
                                'cowardly', 'deceitful', 'dishonest', 'fussy', 'greedy', 'grumpy', 'harsh', 'impatient',
                                'impulsive', 'jealous', 'moody', 'narrow-minded', 'overcritical', 'rude', 'selfish',
                                'untrustworthy', 'unhappy', 'aloof', 'armchair', 'critic', 'big-headed', 'busy body',
                                'couch potato', 'cynical', 'full of hot air', 'goody-goody', 'goody two shoes',
                                'grumpy', 'impulsive', 'indecisive', 'know it all', 'materialistic', 'obnoxious',
                                'pain in the neck', 'picky', 'set in one’s ways', 'tactless', 'thoughtless',
                                'wet blanket', 'party pooper', 'spoilsport', 'killjoy','stick-in-the-mud'],
              'adjetives_pos': ['able', 'abundant', 'aboveboard', 'acceptable', 'accurate', 'achieving', 'affordable',
                                'adaptable', 'ambitious', 'calculated', 'captivated', 'careful', 'casual', 'calm',
                                'capable', 'certain', 'charming', 'cheerful', 'cheery', 'cherished', 'chic', 'civil',
                                'clean', 'comfortable', 'cooperative', 'cordial', 'crafty', 'cute', 'clever', 'natural',
                                'naturalistic', 'neutral', 'newborn', 'needed', 'neat', 'necessary', 'new', 'nifty',
                                'nice', 'nontoxic', 'notable', 'nourishing', 'novel', 'nurturant', 'tactful',
                                'talented', 'tasty', 'taxing', 'teachable', 'thankful', 'thoughtful', 'through',
                                'thrifty', 'thrilled', 'thriving', 'timeless', 'tolerant', 'top-notch', 'touching',
                                'twinkly', 'terrific', 'truthful', 'trusting', 'trustworthy', 'trusted', 'tremendous',
                                'treasured', 'tranquil', 'tidy', 'tantalizing', 'toned', 'tricky', 'tasteful',
                                'triumphant', 'perfect', 'reasonable', 'luxurious', 'kind-hearted', 'justified',
                                'wonderful', 'heroic', 'glamorous', 'forgiving', 'expressive', 'valuable', 'dapper',
                                'stunning', 'beloved', 'dazzled', 'excellent', 'flashy', 'healing', 'legit',
                                'optimistic', 'peaceful', 'romantic', 'loving', 'faithful', 'soothing'],
              'who_general': ['family', 'familiar', 'relatives', 'companion', 'apprentice', 'artist', 'assistant',
                              'buddy', 'director', 'manager', 'specialist', 'student', 'youth', 'young', 'leader',
                              'partner', 'neighbor', 'accountant', 'actor', 'actress', 'architect', 'astronomer',
                              'author', 'baker', 'bricklayer', 'bus driver', 'butcher', 'carpenter', 'chef', 'cook',
                              'cleaner', 'dentist', 'designer', 'doctor', 'dustman', 'refuse collector', 'electrician',
                              'engineer', 'factory', 'farmer', 'fireman', 'fire', 'fisherman', 'florist', 'gardener',
                              'hairdresser', 'journalist', 'judge', 'lawyer', 'lecturer', 'librarian', 'lifeguard',
                              'mechanic', 'model', 'newsreader', 'nurse', 'optician', 'painter', 'pharmacist',
                              'photographer', 'pilot', 'plumber', 'politician', 'policeman', 'policewoman', 'postman',
                              'real', 'receptionist', 'scientist', 'secretary', 'shop', 'soldier', 'tailor', 'taxi',
                              'teacher', 'translator', 'traffic warden', 'travel agent', 'veterinary doctor', 'waiter',
                              'waitress', 'window cleaner'],
              'who_male': ['grandfather', 'mayor', 'doctor', 'pupil', 'pupils', 'friend', 'friends', 'advisor', 'child',
                           'buddy', 'companion', 'colleagues', 'dean', 'director', 'doctor', 'employee', 'entrepreneur',
                           'coach', 'husband', 'expert', 'experts', 'officer', 'brother', 'engineer', 'researcher',
                           'boss', 'player', 'father', 'doctor', 'boy', 'boys', 'child', 'children', 'boyfriend', 'son',
                           'cousin', 'dad', 'kids', 'teacher', 'kid', 'secretary', 'partner', 'tutor', 'daddy', 'uncle',
                           'grandchild'],
              'who_female': ['advisor', 'child', 'mother', 'companion', 'companion', 'lady', 'dean', 'director',
                             'doctor', 'employee', 'entrepreneur', 'wife', 'expert', 'officer', 'sister', 'engineer',
                             'researcher', 'boss', 'player', 'mother', 'mother', 'doctor', 'girl', 'girls', 'woman',
                             'girls', 'bride', 'novice', 'daughter', 'cousin', 'little', 'little', 'teacher',
                             'secretary', 'lady', 'partner', 'tutor', 'mommy', 'aunt', 'granddaughter'],
              'hate': ['animosity', 'antagonism', 'enmity', 'hatred', 'horror', 'hostility', 'loathing', 'pain',
                       'rancor', 'resentment', 'revenge', 'venom', 'abhorrence', 'abomination', 'anathema', 'animus',
                       'antipathy', 'aversion', 'bother', 'bugbear', 'detestation', 'disgust', 'execration', 'frost',
                       'grievance', 'gripe', 'irritant', 'malevolence', 'malignity', 'nuisance', 'objection', 'odium',
                       'rankling', 'repugnance', 'repulsion','revulsion', 'scorn', 'spite', 'trouble', 'black beast',
                       'bête noire', 'ill will', 'mislike', 'nasty look', 'no love lost']
              
              }